# Generated by Django 2.0.5 on 2018-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0017_auto_20181024_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
