# Generated by Django 2.0.5 on 2018-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0018_auto_20181024_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='img_path',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
