# Generated by Django 2.0.5 on 2018-10-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0019_victim_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='img_path',
        ),
    ]
