# Generated by Django 2.0.5 on 2018-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0020_remove_victim_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=21),
        ),
    ]
