name: default-work-dir

on:
  push:
    branches:
    - master

jobs:
  work-dir:
    name: Default Working DIR
    runs-on: ubuntu-latest

    steps:
    - name: Run PWD command
      run: |
        pwd
        find .
        cd $GITHUB_WORKSPACE
        pwd
        find .
